### ISSUE TITLE
Error on startup -- docker latest (previously worked on 4.6.3)

### ISSUE THREAD

**Issue by yieldhog** [squidfunk/mkdocs-material#1625]
## Description

First of all, great project. I have had installed on a docker image (using squidfunk/mkdocs-material official image), running successfully on my Synology 918+.

I am receiving an error on start-up, as follows (from logs) where the docker container then stops -- any help appreciated.

```
squidfunk-mkdocs-material
date,stream,content
2020-04-18 14:29:43,stdout,AttributeError: 'dict' object has no attribute 'split'

2020-04-18 14:29:43,stdout,    return '/'.join(path.split('\\'))

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/mkdocs/utils/__init__.py\", line 251, in path_to_url
"
2020-04-18 14:29:43,stdout,    path = path_to_url(path or '.')

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/mkdocs/utils/__init__.py\", line 223, in normalize_url
"
2020-04-18 14:29:43,stdout,"    return normalize_url(value, page=context['page'], base=context['base_url'])
"
2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/mkdocs/utils/filters.py\", line 14, in url_filter
"
2020-04-18 14:29:43,stdout,    <img src="{{ config.theme.logo | url }}" alt="logo">

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/material/partials/logo.html\", line 5, in top-level template code
"
2020-04-18 14:29:43,stdout,    {% include "partials/logo.html" %}

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/material/partials/header.html\", line 7, in top-level template code
"
2020-04-18 14:29:43,stdout,    {% include "partials/header.html" %}

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/material/base.html\", line 109, in block \"header\"
"
2020-04-18 14:29:43,stdout,    {% block header %}

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/material/base.html\", line 108, in top-level template code
"
2020-04-18 14:29:43,stdout,    {% extends "base.html" %}

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/material/404.html\", line 4, in top-level template code
"
2020-04-18 14:29:43,stdout,    raise value.with_traceback(tb)

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/jinja2/_compat.py\", line 28, in reraise
"
2020-04-18 14:29:43,stdout,    reraise(*rewrite_traceback_stack(source=source))

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/jinja2/environment.py\", line 832, in handle_exception
"
2020-04-18 14:29:43,stdout,    self.environment.handle_exception()

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/jinja2/environment.py\", line 1090, in render
"
2020-04-18 14:29:43,stdout,    output = template.render(context)

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py\", line 93, in _build_template
"
2020-04-18 14:29:43,stdout,"    output = _build_template(template_name, template, files, config, nav)
"
2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py\", line 114, in _build_theme_template
"
2020-04-18 14:29:43,stdout,"    _build_theme_template(template, env, files, config, nav)
"
2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/mkdocs/commands/build.py\", line 288, in build
"
2020-04-18 14:29:43,stdout,"    build(config, live_server=live_server, dirty=dirty)
"
2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/mkdocs/commands/serve.py\", line 136, in builder
"
2020-04-18 14:29:43,stdout,    config = builder()

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/mkdocs/commands/serve.py\", line 141, in serve
"
2020-04-18 14:29:43,stdout,    serve.serve(

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py\", line 140, in serve_command
"
2020-04-18 14:29:43,stdout,"    return callback(*args, **kwargs)
"
2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 610, in invoke
"
2020-04-18 14:29:43,stdout,"    return ctx.invoke(self.callback, **ctx.params)
"
2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke
"
2020-04-18 14:29:43,stdout,    return _process_result(sub_ctx.command.invoke(sub_ctx))

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke
"
2020-04-18 14:29:43,stdout,    rv = self.invoke(ctx)

2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 782, in main
"
2020-04-18 14:29:43,stdout,"    return self.main(*args, **kwargs)
"
2020-04-18 14:29:43,stdout,"  File \"/usr/local/lib/python3.8/site-packages/click/core.py\", line 829, in __call__
"
2020-04-18 14:29:43,stdout,    sys.exit(cli())

2020-04-18 14:29:43,stdout,"  File \"/usr/local/bin/mkdocs\", line 8, in <module>
"
2020-04-18 14:29:43,stdout,Traceback (most recent call last):

2020-04-18 14:29:42,stdout,INFO    -  Cleaning site directory 

2020-04-18 14:29:38,stdout,INFO    -  Building documentation... 
```

### Package versions

* MkDocs material: 5.1.1 (official docker image)

### Project configuration

``` yaml
# Project information
site_name: 'My title
site_description: ''
site_author: 'Yieldhog'
site_url: http://192.168.1.X:XX
repo_name: 'my name'
repo_url: 'my url'
copyright: 'Copyright 2020'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'my url'

# Theme configuration
theme:
  name: 'material'
  logo:
    icon: 'home'

# Extensions
# https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true

# Pages to serve
nav:
  - Home: index.md
```

### System information

* OS: Synology 918+

**Comment by squidfunk** [comment]
See #1579

**Comment by yieldhog** [comment]
Thank you
