### ISSUE TITLE
Social plugin crashes when font autoloading is disabled

### ISSUE THREAD

**Issue by joserebelo** [squidfunk/mkdocs-material#7118]
### Bug description

After updating from v9.5.18 to v9.5.19, the social plugin now ffails:

```
Traceback (most recent call last):
  File "/storage/workspace/Freeyourgadget/website/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 284, in build_command
    build.build(cfg, dirty=not clean)
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 265, in build
    config = config.plugins.on_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/mkdocs/plugins.py", line 587, in on_config
    return self.run_event('config', config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 160, in on_config
    self.font = self._load_font(config)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/workspace/Freeyourgadget/website/.venv/lib/python3.11/site-packages/material/plugins/social/plugin.py", line 452, in _load_font
    name = config.theme.get("font", {}).get("text", "Roboto")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'get'
```

### Related links

- This is following the autoloading disabling configuration mentioned in https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=font#autoloading
- I believe the regression was introduced by https://github.com/squidfunk/mkdocs-material/commit/6a761ed418f6daaeaae313971e7d653fe1599661

### Reproduction

[docs.zip](https://github.com/squidfunk/mkdocs-material/files/15142025/docs.zip)

### Steps to reproduce

1. Use the social plugin
2. Set `font: false` in the theme configuration
3. Notice the build fails

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Indeed, this seems to be a regression. Note that this does not happen in Insiders, only in the communiy edition. We'll look into it.

**Comment by squidfunk** [comment]
Released as part of [9.5.20](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.20).
